apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: shipwright-operator
  name: system
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: operator
  namespace: system
spec:
  sourceType: grpc
  image: docker.io/ayushsatyam146/operator-catalog:v0.13.0-rc0
  displayName: Shipwright Operator Catalog
  publisher: The Shipwright Contributors
  updateStrategy:
    registryPoll:
      interval: 10m